# Site settings
title: Coding With Dee 
header-img: img/home-bg.png
email: hey@deeraceart.com
copyright_name: Dee-Race
description: > # this means to ignore newlines until "baseurl:"
  // Follow along as I learn to code in rural Maine //
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Dee-Race
learn_profile: Dee-Race
email_username: hey@deeraceart.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
